apiVersion: v1
kind: Service
metadata:
    name: cbapis-loadbalancer-dev
    namespace: cbapis-dev
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
spec:
    type: LoadBalancer
    selector:
        app: cbapis
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
