apiVersion: v1
kind: Service
metadata:
    name: cbapis-service-dev
    namespace: cbapis-dev
    labels:
        app: cbapis
spec:
    type: NodePort
    selector:
        app: cbapis
    ports:
        - name: http
          port: 8080
          targetPort: 8080
