apiVersion: v1
kind: Service
metadata:
    name: cbapis-service-uat
    namespace: cbapis-uat
    labels:
        app: cbapis
spec:
    type: ClusterIP
    selector:
        app: cbapis
    ports:
        - name: http
          port: 8080
          targetPort: 8080
