# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Njk1MzJkYWQ2YjlmOTk0ZTQ0ZjU4OTRkY2E2ZjBiZDYzYWZmYzE0MDM0NWM0OTM1YmJmYzUxN2QxYjI1NDEyZjFjYmVjNzZiNWUwY2Q5NGE0Zjc0NGVhZWVlNGZjNGRlOTY5ODcyZTdiY2UyMzgxN2JjYWRlZTkxZjk5MmUwZDQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
